name: Chaos Hunting Workfloww

on:
  push:
    branches:
      - main

jobs:
  dirsearch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install packages
      run: |
        pip install httpx google-auth gdown dirsearch
    - name: Download urls txt file
      run: |
        gdown --id 1w4pQll27LK5l2Z7UrHY179MtIR_FFrQA --output urls.txt
    - name: Download wordlist txt file
      run: |
        wget https://raw.githubusercontent.com/sureshsharma099/.github-workflows/main/.github/workflows/wordlist.txt -o wordlist.txt
    - name: Run dirsearch
      run: |
        dirsearch -u urls.txt -w wordlist.txt -t 5 --format plain -o result.txt
    - name: Get page titles
      run: |
        for url in $(cat result.txt | grep "200 OK" | cut -d ' ' -f3); do
          title=$(httpx -title $url);
          echo "$title $url" >> result.txt;
        done
    - name: Send results to Discord
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        message: "New result found: $(cat result.txt)"
