name: SBX Hunting Workflow

on:
  push:
    branches:
      - main

jobs:
  dirsearch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install packages
      run: |
        pip install httpx dirsearch
    - name: Install GNU parallel
      run: sudo apt-get update && sudo apt-get -y install parallel
    - name: Download urls txt file
      run: |
        wget https://raw.githubusercontent.com/sureshsharma099/.github-workflows/main/.github/workflows/sbx.txt -O urls.txt
    - name: Download wordlist txt file
      run: |
        wget https://raw.githubusercontent.com/sureshsharma099/.github-workflows/main/.github/workflows/swagger.txt -O wordlist.txt
    - name: Run dirsearch for each URL in urls.txt
      run: |
        curl -H "Content-Type: application/json" -X POST -d '{"content": "SBX Hunting Workflow"}' https://discord.com/api/webhooks/1079741266520186951/TGX2RNq4Wc8daXCR06AhqRCarr1xnMd4GSZheVQlFatI3MLKZOerYx4aahLYKineyEpr
        cat urls.txt | parallel --jobs 20 "dirsearch -u {} -w wordlist.txt -t 20 --include-status=\"200,301,302\" --user-agent='Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0' --format plain -o temp.txt && if [ -f temp.txt ]; then cat temp.txt | tail -n +2 | awk 'NF' | awk '{print $3}' | tee -a result.txt && curl -H "Content-Type: application/json" -X POST -d '{"content": "\n```'"$(cat result.txt)"'```"}' https://discord.com/api/webhooks/1079741266520186951/TGX2RNq4Wc8daXCR06AhqRCarr1xnMd4GSZheVQlFatI3MLKZOerYx4aahLYKineyEpr && rm temp.txt; fi"
        curl -H "Content-Type: application/json" -X POST -d '{"content": "$(cat result.txt)"}' https://discord.com/api/webhooks/1079741266520186951/TGX2RNq4Wc8daXCR06AhqRCarr1xnMd4GSZheVQlFatI3MLKZOerYx4aahLYKineyEpr
        if [ -s "result.txt" ]; then
          cat result.txt
          curl -H "Content-Type: application/json" -X POST -d '{"content": "$(cat result.txt)"}' https://discord.com/api/webhooks/1079741266520186951/TGX2RNq4Wc8daXCR06AhqRCarr1xnMd4GSZheVQlFatI3MLKZOerYx4aahLYKineyEpr
        fi
        bashupload=$(curl bashupload.com -T result.txt)
        curl -H "Content-Type: application/json" -X POST -d '{"content": "$(echo "$bashupload")"}' https://discord.com/api/webhooks/1079741266520186951/TGX2RNq4Wc8daXCR06AhqRCarr1xnMd4GSZheVQlFatI3MLKZOerYx4aahLYKineyEpr
    - name: Get page titles and send valid URLs to Discord
      run: |
        valid_urls=""
        while read url; do
          title=$(httpx -title "$url")
          if [[ "$title" != "" ]]; then
            echo "$url $title" >> valid_result.txt
            valid_urls+="$url\n"
          fi
        done < result.txt
        if [[ "$valid_urls" != "" ]]; then
          echo "Valid result found: $valid_urls"
          curl -H "Content-Type: application/json" -X POST -d '{"content": "OVERALL RESULT BELOW"}' https://discord.com/api/webhooks/1079741266520186951/TGX2RNq4Wc8daXCR06AhqRCarr1xnMd4GSZheVQlFatI3MLKZOerYx4aahLYKineyEpr          
          curl -H "Content-Type: application/json" -X POST -d '{"content": "$(cat valid_result.txt)"}' https://discord.com/api/webhooks/1079741266520186951/TGX2RNq4Wc8daXCR06AhqRCarr1xnMd4GSZheVQlFatI3MLKZOerYx4aahLYKineyEpr
        else
          echo "No valid results found"
        fi
